### ISSUE TITLE
Feature to Command mapping

### ISSUE THREAD

**Issue by ecdpalma** [receipt-print-hq/escpos-printer-db#33]
Just a suggestion...

It would be interesting if we could map the commands for common features across various printer models and include these mappings in the printer profile.

**Comment by mike42** [comment]
Good suggestion, thanks for the taking the time to share.

I'm generally open to reviewing pull requests to add new fields to the database if there is a downstream projects that has a use for them. eg, a really good pull request would be "I need X fields added, so that I can achieve Y in projects Z and W, and here are the values for printers A, B and C with some sensible defaults for the rest".

I don't believe that it's a good idea to host data in this repo beyond what we actually use as part of an implementation (there are some IP and maintainability issues around that), so I'm going to close this off until that happens.

If you've got a printer, make sure it's in the database, too. ;)
