### ISSUE TITLE
Add a new 'dpi' field to include the printer's DPI resolution

### ISSUE THREAD

**Issue by belono** [receipt-print-hq/escpos-printer-db#80]
Greetings!

We are adding some [new features](https://github.com/python-escpos/python-escpos/pull/527#issue-1735053881) to the [python-escpos](https://github.com/python-escpos/python-escpos) library that makes use of this great escpos-printer-db capabilities database.
One of this new features will be the ability to match the sizes of hardware and software-generated bar-codes by rendering bar-code images of the same resolution as the printer's native resolution, but in order to make the appropriate calculations we previously need to know the printer’s DPI value that varies between the different models.

Our request is that a new field named `dpi` would be added into the `media` group of the profiles to include the DPI resolution of the listed printers so this information can be fetched by any client.
 The idea is that the `default.yml` profile would contain the inheritable `media: dpi: Unknown` items, so that each profile can be overloaded with the right value when known.

I’d be glad to start a PR with the necessary changes, as soon as I have the time, if you agree with this proposal.

Thanks in advance.

**Comment by patkan** [comment]
@mike42 What do you think about this? As far as @belono has described it, the value could be guessed from media sizes, but this is not very reliable since the printable area varies from printer to printer. An actual dpi value would help with this change (but in the end also with other changes where you try to scale something to a certain size)
